import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistNotoSansKR = localFont({
  src: "../../public/font/NotoSansKR.ttf",
  variable: "--font-geist-NotoSansKR",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistNotoSansKR.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
